version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: Net5CoreWebAPI/Dockerfile
    restart: always
    ports:
      - 5000:80
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
    # frontend:
    #     container_name: clientapp
    #     build:
    #         context: .
    #         dockerfile: ClientApp/Dockerfile-Development
    #     restart: always
    #     volumes:
    #         - ./ClientApp:/app
    #     ports:
    #         - 4200:4200
    #     command: npm start