version: '3'

services:
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: Net5CoreWebAPI/Dockerfile
    restart: always
    ports:
      - 5000:80
    depends_on:
      - db